import { jsPDF } from "jspdf";
import { autoTable } from "jspdf-autotable";
import type { ReportTablePayload } from "./report.types.js";

const INSTITUTION_FALLBACK = "Enhance Education";
const BRAND = {
  ink: [0, 44, 35] as [number, number, number],
  amber: [219, 144, 39] as [number, number, number],
  muted: [124, 138, 132] as [number, number, number],
  line: [220, 211, 198] as [number, number, number],
  white: [255, 255, 255] as [number, number, number],
};

type PdfDoc = jsPDF & { lastAutoTable?: { finalY: number } };

export function renderAdminAiReportPdf(input: {
  institutionName?: string | null;
  generatedAtLabel: string;
  payload: ReportTablePayload;
}): Buffer {
  const doc = new jsPDF({ orientation: "portrait", unit: "mm", format: "a4" });
  const pageWidth = doc.internal.pageSize.getWidth();
  const margin = 14;
  const institution = input.institutionName?.trim() || INSTITUTION_FALLBACK;

  doc.setFillColor(...BRAND.ink);
  doc.rect(0, 0, pageWidth, 18, "F");
  doc.setFillColor(...BRAND.amber);
  doc.rect(0, 18, pageWidth, 1.4, "F");

  doc.setTextColor(...BRAND.white);
  doc.setFont("helvetica", "bold");
  doc.setFontSize(12);
  doc.text(institution, margin, 8);
  doc.setFont("helvetica", "normal");
  doc.setFontSize(9);
  doc.text(input.payload.title, margin, 14);

  let y = 28;
  doc.setTextColor(...BRAND.ink);
  doc.setFont("helvetica", "bold");
  doc.setFontSize(14);
  doc.text(input.payload.title, margin, y);
  y += 6;

  doc.setFont("helvetica", "normal");
  doc.setFontSize(8);
  doc.setTextColor(...BRAND.muted);
  doc.text(`Generated ${input.generatedAtLabel}`, margin, y);
  y += 6;

  if (input.payload.filterLabels.length) {
    doc.setTextColor(...BRAND.ink);
    doc.setFont("helvetica", "bold");
    doc.setFontSize(9);
    doc.text("Filters", margin, y);
    y += 4;
    doc.setFont("helvetica", "normal");
    doc.setFontSize(8);
    doc.setTextColor(...BRAND.muted);
    for (const label of input.payload.filterLabels.slice(0, 8)) {
      doc.text(`• ${label}`, margin, y);
      y += 4;
    }
    y += 2;
  }

  if (input.payload.summary.length) {
    doc.setTextColor(...BRAND.ink);
    doc.setFont("helvetica", "bold");
    doc.setFontSize(9);
    doc.text("Summary", margin, y);
    y += 4;
    doc.setFont("helvetica", "normal");
    doc.setFontSize(8);
    for (const item of input.payload.summary.slice(0, 8)) {
      doc.setTextColor(...BRAND.muted);
      doc.text(`${item.label}: ${item.value}`, margin, y);
      y += 4;
    }
    y += 2;
  }

  if (input.payload.truncated) {
    doc.setTextColor(...BRAND.amber);
    doc.setFontSize(8);
    doc.text(
      "Note: Results were limited for report size. Narrow filters for a full export.",
      margin,
      y,
    );
    y += 6;
  }

  autoTable(doc, {
    startY: Math.max(y, 42),
    head: [input.payload.columns],
    body: input.payload.rows,
    margin: { left: margin, right: margin },
    styles: {
      fontSize: 8,
      cellPadding: 2,
      textColor: BRAND.ink,
      lineColor: BRAND.line,
      lineWidth: 0.1,
    },
    headStyles: {
      fillColor: BRAND.ink,
      textColor: BRAND.white,
      fontStyle: "bold",
    },
    alternateRowStyles: {
      fillColor: [251, 248, 243],
    },
  });

  const pdf = doc as PdfDoc;
  const pageCount = doc.getNumberOfPages();
  for (let page = 1; page <= pageCount; page += 1) {
    doc.setPage(page);
    const pageHeight = doc.internal.pageSize.getHeight();
    const footerY = pageHeight - 8;
    doc.setDrawColor(...BRAND.line);
    doc.setLineWidth(0.2);
    doc.line(margin, footerY - 4, pageWidth - margin, footerY - 4);
    doc.setFont("helvetica", "normal");
    doc.setFontSize(7);
    doc.setTextColor(...BRAND.muted);
    doc.text("Generated by Enhance", margin, footerY);
    doc.text(
      `Page ${page} of ${pageCount}`,
      pageWidth - margin,
      footerY,
      { align: "right" },
    );
  }

  void pdf;
  const arrayBuffer = doc.output("arraybuffer");
  return Buffer.from(arrayBuffer);
}
